# Generated by Django 3.1.7 on 2021-09-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Is open',
            field=models.BooleanField(default=True),
        ),
    ]
